ALTER TABLE players ADD COLUMN total_ram_mb INTEGER NOT NULL DEFAULT 1024;
ALTER TABLE players ADD COLUMN total_cpu_cores INTEGER NOT NULL DEFAULT 1;

ALTER TABLE servers ADD COLUMN allocated_cpu_cores INTEGER NOT NULL DEFAULT 1;